<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="$(MediatorPackageVersion)" />
    <PackageReference Include="Scrutor" Version="$(ScrutorPackageVersion)" />
  </ItemGroup>  
  
  <ItemGroup>
    <ProjectReference Include="..\NBB.Messaging.Abstractions\NBB.Messaging.Abstractions.csproj" />
  </ItemGroup>

</Project>
