// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NBB.Contracts.ReadModel.Data;
using System;

namespace NBB.Contracts.Migrations.ReadModelMigrations
{
    [DbContext(typeof(ContractsReadDbContext))]
    [Migration("20180402122136_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NBB.Contracts.ReadModel.ContractLineReadModel", b =>
                {
                    b.Property<Guid>("ContractLineId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContractId");

                    b.Property<decimal>("Price");

                    b.Property<string>("Product");

                    b.Property<int>("Quantity");

                    b.HasKey("ContractLineId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractLines");
                });

            modelBuilder.Entity("NBB.Contracts.ReadModel.ContractReadModel", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<Guid>("ClientId");

                    b.Property<bool>("IsValidated");

                    b.Property<int>("Version");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("NBB.Contracts.ReadModel.ContractLineReadModel", b =>
                {
                    b.HasOne("NBB.Contracts.ReadModel.ContractReadModel")
                        .WithMany("ContractLines")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
