<Project>
	<PropertyGroup Label="Package Versions">
		<NewtonsoftJsonPackageVersion>13.0.4</NewtonsoftJsonPackageVersion>
		<MediatorPackageVersion>3.0.2</MediatorPackageVersion>
		<ScrutorPackageVersion>7.0.0</ScrutorPackageVersion>
		<BenchmarkDotNetPackageVersion>0.15.8</BenchmarkDotNetPackageVersion>
		<MoqPackageVersion>4.20.72</MoqPackageVersion>
		<XunitPackageVersion>2.9.3</XunitPackageVersion>
		<XunitRunnerVisualStudioPackageVersion>3.1.5</XunitRunnerVisualStudioPackageVersion>
		<CoverletCollectorPackageVersion>6.0.4</CoverletCollectorPackageVersion>
		<MicrosoftNetTestSdkPackageVersion>18.0.1</MicrosoftNetTestSdkPackageVersion>
		<FsUnitPackageVersion>7.1.1</FsUnitPackageVersion>
		<FluentAssertionsPackageVersion>8.8.0</FluentAssertionsPackageVersion>
		<MicrosoftDataSqlClientPackageVersion>6.1.3</MicrosoftDataSqlClientPackageVersion>
		<MicrosoftExtensionsPackagesVersion>10.0.9</MicrosoftExtensionsPackagesVersion>
		<MicrosoftEntityFrameworkPackagesVersion>10.0.9</MicrosoftEntityFrameworkPackagesVersion>
		<MicrosoftCSharpPackageVersion>4.7.0</MicrosoftCSharpPackageVersion>
		<OpenTelemetryCorePackageVersion>1.16.0</OpenTelemetryCorePackageVersion>
		<OpenTelemetryExtensionsHostingPackageVersion>1.14.0</OpenTelemetryExtensionsHostingPackageVersion>
		<OpenTelemetryExtensionsPropagatorsPackageVersion>1.16.0</OpenTelemetryExtensionsPropagatorsPackageVersion>
		<OpenTelemetryInstrumentationAspNetCorePackageVersion>1.14.0</OpenTelemetryInstrumentationAspNetCorePackageVersion>
		<OpenTelemetryInstrumentationEFCorePackageVersion>1.14.0-beta.1</OpenTelemetryInstrumentationEFCorePackageVersion>
		<OpenTelemetryInstrumentationHttpPackageVersion>1.14.0</OpenTelemetryInstrumentationHttpPackageVersion>
		<OpenTelemetryInstrumentationRuntimePackageVersion>1.14.0</OpenTelemetryInstrumentationRuntimePackageVersion>
		<OpenTelemetryExporterPrometheusHttpListenerPackageVersion>1.14.0-beta.1</OpenTelemetryExporterPrometheusHttpListenerPackageVersion>
		<OpenTelemetryExporterPrometheusAspnetCorePackageVersion>1.14.0-beta.1</OpenTelemetryExporterPrometheusAspnetCorePackageVersion>
		<PollyVersion>8.6.5</PollyVersion>
		<SerilogPackageVersion>4.3.0</SerilogPackageVersion>
		<SerilogExtensionsLoggingPackageVersion>10.0.0</SerilogExtensionsLoggingPackageVersion>
		<SerilogExtensionsHostingPackageVersion>10.0.0</SerilogExtensionsHostingPackageVersion>
		<SerilogSinksConsole>6.1.1</SerilogSinksConsole>
		<SerilogSinksMSSqlServerPackageVersion>9.0.2</SerilogSinksMSSqlServerPackageVersion>
		<SerilogAspNetCorePackageVersion>10.0.0</SerilogAspNetCorePackageVersion>
		<MapperlyPackageVersion>4.3.1</MapperlyPackageVersion>
		<NJsonSchemaPackageVersion>11.5.2</NJsonSchemaPackageVersion>
		<AutoFixturePackageVersion>4.18.1</AutoFixturePackageVersion>
		<JaegerPackageVersion>1.0.3</JaegerPackageVersion>
		<SystemIdentityModelTokensJwtPackageVersion>8.15.0</SystemIdentityModelTokensJwtPackageVersion>
	</PropertyGroup>
</Project>
