apiVersion: v1
kind: Service
metadata:
  name: nbb-docfx-v4
  labels:
    app: nbb-docfx-v4
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    app: nbb-docfx-v4
  type: ClusterIP
---