apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbb-docfx-v4
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nbb-docfx-v4
  template:
    metadata:
      labels:
        app: nbb-docfx-v4
    spec:
      containers:
      - name: nbb-docfx
        image: tsacr.azurecr.io/nbb_docfx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
      imagePullSecrets:
      - name: registrykey
---